on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

     # - name: Set up Java
     #   uses: actions/setup-java@v1
     #   with:
     #     java-version: '12.x'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.6'
          channel: 'stable'
          
      - name: Clean project
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Build APK
        run: flutter build apk --release
        
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: QA build
          path: build/app/outputs/flutter-apk/app-release.apk

